# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191128_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contacts',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='positions',
            new_name='position',
        ),
    ]
