# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-19 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191128_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_security',
            field=models.BooleanField(default=False),
        ),
    ]
