# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.CharField(max_length=40)),
                ('cocategory', models.CharField(max_length=40)),
                ('costatus', models.CharField(max_length=40)),
                ('codescrp', models.CharField(max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
