# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loname', models.CharField(max_length=40)),
                ('lostatus', models.CharField(max_length=40)),
                ('lodescrp', models.CharField(max_length=40)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
