# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-06 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0003_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonassets',
            name='is_assigned',
            field=models.IntegerField(null=True),
        ),
    ]
