# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-06 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_asset', '0005_assetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('itemid', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('asgn_location', models.CharField(max_length=100)),
                ('assgn_status', models.IntegerField()),
                ('assign_on', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
