# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-06 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0007_auto_20191206_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conassets',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
