# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0008_auto_20191206_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='request_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
