# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0009_auto_20191206_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='lended_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=100)),
                ('staffid', models.CharField(max_length=20)),
                ('itemname', models.CharField(max_length=100)),
                ('itemid', models.CharField(max_length=100)),
                ('where_itgo', models.CharField(max_length=100)),
                ('descript', models.CharField(max_length=100)),
                ('lend_status', models.IntegerField()),
                ('lend_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
