# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0011_lended_assets_recivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lended_assets',
            name='descript',
            field=models.CharField(max_length=255),
        ),
    ]
