# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-06 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0013_auto_20200306_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='conassets',
            name='updated_on',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 10, 0, 52, 148138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='conassets',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
