# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-06 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0015_auto_20200306_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conassets',
            name='updated_on',
            field=models.DateField(default=datetime.datetime(2020, 3, 6, 10, 2, 56, 439839, tzinfo=utc)),
        ),
    ]
