# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0016_auto_20200306_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conassets',
            name='updated_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
