# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-06 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0017_auto_20200306_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conassets',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
