# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-06 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0018_auto_20200306_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='edited_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_edit', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('itemid', models.CharField(max_length=100)),
                ('edited_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deleted_assets',
            name='user_delete',
            field=models.CharField(max_length=100),
        ),
    ]
