# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-07 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0020_nonassets_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='lost_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_edit', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('itemid', models.CharField(max_length=100)),
                ('edited_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lended_assets',
            name='lend_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
