# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-11 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0024_auto_20200311_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='lostatus',
            field=models.BooleanField(default=True),
        ),
    ]
