# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0026_auto_20200311_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_assets',
            name='assgn_status',
            field=models.IntegerField(default=0),
        ),
    ]
