# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0028_auto_20200311_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lended_assets',
            name='lend_status',
        ),
        migrations.AddField(
            model_name='lended_assets',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
