# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-18 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0029_auto_20200311_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonassets',
            name='is_verified_today',
            field=models.BooleanField(default=False),
        ),
    ]
