# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0030_nonassets_is_verified_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='lodescrp',
            field=models.CharField(max_length=200),
        ),
    ]
