# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-08 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0032_security_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security_report',
            name='day',
        ),
    ]
