# Generated by Django 3.2.4 on 2021-06-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0034_asset_auto_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_auto_tracking',
            name='asset_id',
            field=models.CharField(max_length=50),
        ),
    ]
