# Generated by Django 3.2.4 on 2022-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0039_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_auto_tracking',
            name='reader_loc',
            field=models.CharField(max_length=200),
        ),
    ]
