# Generated by Django 3.2.15 on 2022-08-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0039_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonassets',
            name='tag_id',
            field=models.CharField(default=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset_auto_tracking',
            name='reader_loc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nonassets',
            name='nocid',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
