# Generated by Django 3.2.15 on 2022-08-31 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0042_auto_20220830_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonassets',
            name='id',
            field=models.AutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nonassets',
            name='nocid',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='nonassets',
            name='tag_id',
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
