# Generated by Django 3.2.15 on 2022-08-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0043_auto_20220831_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonassets',
            name='tag_id',
            field=models.CharField(default=True, max_length=255, unique=True),
        ),
    ]
