# Generated by Django 3.2.15 on 2022-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0044_alter_nonassets_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonassets',
            name='tag_id',
            field=models.CharField(default=True, max_length=255, null=True, unique=True),
        ),
    ]
