# Generated by Django 3.2.15 on 2022-08-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0040_auto_20220831_1026'),
        ('manage_asset', '0045_alter_nonassets_tag_id'),
    ]

    operations = [
    ]
