# Generated by Django 3.2.15 on 2022-08-31 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0046_merge_20220831_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonassets',
            name='id',
        ),
        migrations.AddField(
            model_name='nonassets',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nonassets',
            name='tag_id',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
