# Generated by Django 3.2.15 on 2022-08-31 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0047_auto_20220831_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonassets',
            name='assets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_asset.asset_auto_tracking'),
        ),
    ]
