# Generated by Django 3.2.15 on 2022-09-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0048_nonassets_assets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonassets',
            old_name='assets',
            new_name='plan',
        ),
    ]
