# Generated by Django 3.2.15 on 2022-09-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0049_rename_assets_nonassets_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonassets',
            old_name='plan',
            new_name='assets',
        ),
    ]
