# Generated by Django 3.2.15 on 2022-09-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0050_rename_plan_nonassets_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonassets',
            name='assets',
        ),
        migrations.AlterField(
            model_name='asset_auto_tracking',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_asset.nonassets'),
        ),
    ]
