# Generated by Django 3.2.15 on 2022-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0051_auto_20220901_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonassets',
            name='nocid',
            field=models.CharField(max_length=40),
        ),
    ]
