# Generated by Django 3.2.15 on 2022-09-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0052_alter_nonassets_nocid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='lodescrp',
        ),
    ]
