# Generated by Django 3.2.15 on 2022-09-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0053_remove_locations_lodescrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_loc', models.CharField(max_length=200)),
                ('default_loc', models.CharField(max_length=200)),
                ('has_changed_loc', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_asset.nonassets')),
            ],
        ),
    ]
