# Generated by Django 3.2.15 on 2022-09-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0054_asset_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonassets',
            name='noclocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_asset.locations'),
        ),
    ]
