# Generated by Django 3.2.15 on 2022-09-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0055_alter_nonassets_noclocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_id', models.CharField(max_length=100)),
                ('door_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('access_door_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_asset.access_doors')),
            ],
        ),
        migrations.CreateModel(
            name='attempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_on', models.DateTimeField(auto_now_add=True)),
                ('access_status', models.BooleanField(default=True)),
                ('door_description', models.CharField(max_length=100)),
                ('access_door_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_asset.access_doors')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_asset.authorization')),
            ],
        ),
    ]
