# Generated by Django 3.2.15 on 2022-09-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0056_access_doors_attempts_authorization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorization',
            old_name='access_door_id',
            new_name='access_id',
        ),
        migrations.RenameField(
            model_name='authorization',
            old_name='card_id',
            new_name='cid',
        ),
    ]
