# Generated by Django 3.2.9 on 2022-09-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0057_auto_20220912_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempts',
            name='access_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempts',
            name='card_id',
            field=models.CharField(max_length=100),
        ),
    ]
