# Generated by Django 3.2.15 on 2022-09-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_asset', '0058_auto_20220912_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempts',
            name='userFullName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
