# Generated by Django 3.2.15 on 2022-09-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userinfo_card'),
        ('manage_asset', '0059_attempts_userfullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='username',
        ),
        migrations.AlterField(
            model_name='authorization',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userinfo'),
        ),
    ]
