# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requested_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('descriptions', models.CharField(max_length=200)),
                ('request_user', models.CharField(max_length=200)),
                ('request_status', models.CharField(max_length=40)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
