# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requested_assets',
            name='request_user_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
