# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-23 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20200223_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested_assets',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
