# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assetissues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nocname', models.CharField(max_length=200)),
                ('nocid', models.CharField(max_length=20)),
                ('problems', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
