# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlinzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=200)),
                ('date_commented', models.DateField(default=django.utils.timezone.now)),
                ('user_comment', models.CharField(max_length=200)),
                ('comment_is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
